name: movie_app
description: "A Flutter movie app using TMDB API"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  carousel_slider: ^5.1.1
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2
  permission_handler: ^12.0.1
  path_provider: ^2.1.1
  dio: ^5.4.0
  open_file: ^3.3.3
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true